workout/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :groups do
    resources :challenges, :only => [:new]
  end
  resources :challenges, :only => [:update, :destroy, :show, :index, :create, :edit] do
    resources :activities, :only => [:new]
  end

  resources :activities, :only => [:update, :destroy, :show, :index, :create, :edit]

  resources :users

  root 'groups#index'

end

workout/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :group
  has_many :activites
end

workout/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.sort
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @group = User.find(params[:id]).group
    if !@group.nil?
      @challenges = @group.challenges
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        # format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username,:group_id)
    end
end

workout/app/helpers/users_helper.rb
module UsersHelper
end

workout/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

workout/app/views/users/edit.html.erb
<% provide(:title, "Edit User") %>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

workout/app/views/users/index.html.erb
<% provide(:title, "User Index") %>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <% if user == current_user%>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

workout/app/views/users/new.html.erb
<% provide(:title, "New User") %>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

workout/app/views/users/show.html.erb
<% provide(:title, "Show User") %>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>
<% if !@group.nil? %>
<p>
  <strong>Member of:</strong>
  <%= @group.name %>
</p>
<p>
  <strong>Current challenges:</strong>
  <% @challenges.each do |challenge| %>
    <br><%= challenge.name %> | <%= link_to 'details', challenge_path(challenge) %>
  <% end %>
</p>
<% end %>
<% if @user == current_user %>
<%= link_to 'Edit', edit_user_path(@user) %> |
<% end %>
<%= link_to 'Back', root_path %>