workout/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :groups do
    resources :challenges, :only => [:new]
  end
  resources :challenges, :only => [:update, :destroy, :show, :index, :create, :edit] do
    resources :activities, :only => [:new]
  end

  resources :activities, :only => [:update, :destroy, :show, :index, :create, :edit]

  resources :users

  root 'groups#index'

end

workout/app/models/challenge.rb
class Challenge < ActiveRecord::Base
  belongs_to :group
  has_many :activities

 def generate_calendar(current_user_id)
    challenge_frequency = self.frequency.downcase
    start = self.created_at
    activities_array = []

    self.activities.each do |activity|
      if activity.user_id == current_user_id
        activities_array << activity
      end
    end

    case challenge_frequency
    when 'daily'
      completion_array = Array.new(duration, false)
      for i in (0..duration)
        start_criteria = start + i.day
        end_criteria = start + (i+1).day
        activities_array.each do |activity|
          if activity.created_at.between?(start_criteria, end_criteria)
            completion_array[i] = true
          end
        end
      end
    when 'weekly'
      completion_array = Array.new(duration/7, false)
      for i in(0..duration).step(7)
        start_criteria = start + i.day
        end_criteria = start + (i+7).day
        if activity.created_at.between?(start_criteria, end_criteria)
          completion_array[i] = true
        end
      end
    end
    return completion_array
  end
end

workout/app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_challenge, only: [:show, :edit, :update, :destroy]

  # GET /challenges
  # GET /challenges.json
  def index
    @challenges = Challenge.all.sort
  end

  # GET /challenges/1
  # GET /challenges/1.json
   def show
    @progress = @challenge.generate_calendar(current_user.id)
    @group = @challenge.group
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
    @challenge.group_id = params[:group_id]
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges
  # POST /challenges.json
  def create
    if params[:frequency] == 'custom'
      params[:frequency] = params[:custom_frequency]
    else
      params[:frequency] = params[:frequency]
    end
    @challenge = Challenge.new(name: params[:name], frequency: params[:frequency], wager: params[:wager], duration: params[:duration],group_id:params[:group_id])

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.json { render :show, status: :created, location: @challenge }
      else
        format.html { render :new }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1
  # PATCH/PUT /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  def destroy
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url, notice: 'Challenge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def challenge_params
    #   params.require(:challenge).permit(:name, :frequency, :wager, :duration)
    # end
end

workout/app/helpers/challenges_helper.rb
module ChallengesHelper
end

workout/app/views/challenges/_form.html.erb
<%= form_for(@challenge) do |f| %>
  <% if @challenge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

      <ul>
      <% @challenge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <form method="post" action="/challenges">
    <div class="field">
      <label for='name'>Name:</label><br>
      <input id='name' name='name'><br>
    </div>
    <div class="field">
      <label for='frequency'>frequency</label><br>
      <select id='frequency' name="frequency">
        <option value='daily'>Daily</option>
        <option value='weekly'>Weekly</option>
        <option value='monthly'>Monthly</option>
        <option value='custom'>Custom</option>
      </select>
    </div>
    <div class="day-checkbox">
      <input type='radio' name="custom_frequency" value="2"> Twice a week<br>
      <input type='radio' name="custom_frequency" value="3"> Three times a week<br>
      <input type='radio' name="custom_frequency" value="4"> Four times a week<br>
      <input type='radio' name="custom_frequency" value="5"> Five times a week<br>
      <input type='radio' name="custom_frequency" value="6"> Six times a week<br>
    </div>
    <div class="field">
      <label for='wager'>Wager:</label><br>
      <input id='wager' name='wager'><br>
    </div>
    <div class="field">
      <label for='duration'>Duration:</label><br>
      <input id='duration' name='duration'><br>
    </div>
    <input type='text' value='<%= @challenge.group_id %>' name='group_id' style='display:none;'>
    <div class="actions">
      <input type="submit" value="submit">
    </div>
</form>
<%end%>

workout/app/views/challenges/edit.html.erb
<h1>Editing challenge</h1>

<%= render 'form' %>

<%= link_to 'Show', @challenge %> |
<%= link_to 'Back', challenges_path %>

workout/app/views/challenges/index.html.erb
<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Frequency</th>
      <th>Wager</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @challenges.each do |challenge| %>
      <tr>
        <td><%= challenge.name %></td>
        <td><%= challenge.frequency %></td>
        <td><%= challenge.wager %></td>
        <td><%= challenge.duration %></td>
        <% if current_user.group == @group %>
          <td>
            <button class="record_activity" id="record_activity_<%= challenge.id %>">Done?</button>
            <button class="done" id='done_<%= challenge.id %>' style="display:none;background-color:green;">Done!</button>
          </td>
        <% end %>
        <% if current_user == @group.admin %>
        <td><%= link_to 'Edit', edit_challenge_path(challenge) %></td>
        <td><%= link_to 'Delete', challenge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

workout/app/views/challenges/new.html.erb
<h1>New challenge</h1>

<%= render 'form' %>

<%= link_to 'Back', challenges_path %>

workout/app/views/challenges/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Group:</strong>
  <%= @group.name %>
</p>


<div class='activity'>
<p>
  <% if current_user.group == @group %>
    <button class="record_activity" id="record_activity_<%= @challenge.id %>">Done?</button>
    <button class="done" id='done_<%= @challenge.id %>' style="display:none;background-color:green;">Done!</button>
  <% end %>
</p>
</div>

<p>
  <strong>Task:</strong>
  <%= @challenge.name %>
</p>

<p>
  <strong>Frequency:</strong>
  <%= @challenge.frequency %>
</p>

<p>
  <strong>Wager:</strong>
  $<%= @challenge.wager %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @challenge.duration %> days
</p>

<p>
  <strong>progress output:</strong><br>
  <% for i in (0..((Time.zone.now - @challenge.created_at)/60/60/24).to_i)%>
    <%= (@challenge.created_at + i.day).httpdate.to_s[0..-14] %>:
      <% if @progress[i] %>
        challenge completed!
      <% elsif (@challenge.created_at + i.day) < Time.zone.now %>
        challenge failed!
      <% else %>
        challenge pending
      <% end %>
    <br>
  <% end %>
</p>

<% if current_user == @group.admin%>
  <%= link_to 'Edit', edit_challenge_path %> |
<% end %>
<%= link_to 'Back', groups_path %>