workout/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :groups do
    resources :challenges, :only => [:new]
  end
  resources :challenges, :only => [:update, :destroy, :show, :index, :create, :edit] do
    resources :activities, :only => [:new]
  end

  resources :activities, :only => [:update, :destroy, :show, :index, :create, :edit]

  resources :users

  root 'groups#index'

end

workout/app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users
  has_many :challenges
  belongs_to :admin, class_name:"User"
end

workout/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all.sort
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @challenges = @group.challenges
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :isPublic, :admin_id)
    end
end

workout/app/helpers/groups_helper.rb
module GroupsHelper
end

workout/app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :isPublic %><br>
    <%= f.check_box :isPublic %>  True
  </div>
  <div class="field" style="display:none;">
    <%= f.label :admin_id %><br>
    <%= f.text_field :admin_id, value:current_user.id %>  True
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

workout/app/views/groups/edit.html.erb
<% provide(:title, "Edit Groups") %>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

workout/app/views/groups/index.html.erb
<% provide(:title, "All Groups") %>

<div class="large-12 columns">
<table class="groups-table">
  <thead>
    <tr>
      <th>Group Name</th>
      <th colspan="3">Details</th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <% if group.isPublic == true %>
      <tr>
        <td><%= group.name %></td>
        <td><%= link_to 'Show', group %></td>
        <% if current_user == group.admin %>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Delete', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>
<% if Group.find_by(admin_id:current_user.id) == nil %>
<%= link_to 'New Group', new_group_path %>
<% end %>
</div>

  

workout/app/views/groups/new.html.erb
<% provide(:title, "New Group") %>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

workout/app/views/groups/show.html.erb
<% provide(:title, "Show Groups") %>
<div class="large-12 columns show-groups">
<p id="notice"><%= notice %></p>
<div class="show-groups-window">
  <div class="row show-groups-row">
    <strong>Name:</strong>
    <%= @group.name %>
  </div>
  
  <div class="row show-groups-row">
    <strong>Public:</strong>
    <%= @group.isPublic %>
  </div>
  
  <div class="row show-groups-row">
    <strong>Admin:</strong>
    <%= @group.admin.username %>
  </div>
  <div class="row show-groups-row">
    <%= render :template=>"challenges/index", :@group=>@group %>
  </div>
  <div class="row show-groups-row">
    <% if current_user == @group.admin %>
    <%= link_to 'Create Challenge',  new_group_challenge_path(@group) %> |
    <%= link_to 'Edit', edit_group_path(@group) %> |
    <% end %>
  </div>
  <div class="row show-groups-row">
    <%= link_to 'Back', groups_path %>
    <% if current_user.group_id != @group.id %>
      <a href='' id='join-group'>Join</a>
    <% end %>
  </div>
<input type='text' value='<%= current_user.id %>' style='display:none;' id='user-id'>
<input type='text' value='<%= @group.id %>' style='display:none;' id='group-id'>
</div>
</div>